repos:
-   repo: https://github.com/pycqa/flake8
    rev: 7.0.0  # Use the latest version
    hooks:
    -   id: flake8
        additional_dependencies: [flake8-docstrings]

# Optional: Add more linters/formatters
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0  # Use the latest version
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
